// Module to hold the different options for the select controls

module.exports = {
    
    // ibu level
    abvLevelSelectOptions: [
        { value: "low", label: "Low"},
        { value: "med", label: "Medium"},
        { value: "high", label: "High"}
    ],

    // states
    stateSelectOptions : [
        { value: "MA", label: "Massachusetts"},
        { value: "VT", label: "Vermont"},
        { value: "NH", label: "New Hampshire"},
        { value: "ME", label: "Maine"},
        { value: "RI", label: "Rhode Island"},
        { value: "CT", label: "Connecticut"},
        { value: "NY", label: "New York"},
        { value: "NJ", label: "New Jersey"},
        { value: "PA", label: "Pennsylvania"},
        { value: "MD", label: "Maryland"},
        { value: "DE", label: "Delaware"},
        { value: "WV", label: "West Virginia"},
        { value: "VA", label: "Virginia"},
        { value: "OH", label: "Ohio"},
        { value: "IL", label: "Illinois"},
        { value: "IN", label: "Indiana"},
        { value: "KT", label: "Kentucky"},
        { value: "TN", label: "Tennessee"},
        { value: "AL", label: "Alabama"},
        { value: "AR", label: "Arkansas"},
        { value: "MI", label: "Mississippi"},
        { value: "LA", label: "Louisiana"},
        { value: "FL", label: "Florida"},
        { value: "GA", label: "Georgia"},
        { value: "SC", label: "South Carolina" },
        { value: "NC", label: "North Carolina" },
        { value: "TX", label: "Texas"},
        { value: "MI", label: "Missouri"},
        { value: "OK", label: "Oklahoma"},
        { value: "NE", label: "Nebraska"},
        { value: "IA", label: "Iowa"},
        { value: "KS", label: "Kansas"},
        { value: "WI", label: "Wisconsin" },
        { value: "MI", label: "Michigan"},
        { value: "MN", label: "Minnesota"},
        { value: "SD", label: "South Dakota"},
        { value: "ND", label: "North Dakota"},
        { value: "WY", label: "Wyoming"},
        { value: "MT", label: "Montana"},
        { value: "ID", label: "Idaho"},
        { value: "OR", label: "Oregon"},
        { value: "WA", label: "Washington"},
        { value: "CA", label: "California" },
        { value: "NV", label: "Nevada"},
        { value: "NM", label: "New Mexico"},
        { value: "AZ", label: "Arizona"},
        { value: "CO", label: "Colorado"},
        { value: "UT", label: "Utah"},
        { value: "AK", label: "Alaska"},
        { value: "HI", label: "Hawaii"}
    ],
}